spring.application.name=contract-onboarding-worker
spring.main.keep-alive=true

zenbpm.rest-url=http://localhost:8080/v1
zenbpm.rest-logging-enabled=true

zenbpm.grpc-host=localhost
zenbpm.grpc-port=9090
zenbpm.grpc-plaintext=true
zenbpm.grpc-logging-enabled=true

zenbpm.job-worker-enabled=true
zenbpm.otel-enabled=false
